version: '3'
services:
  rapidscyber:
    build: .
    ports:
      - "8888:8888"
      - "8787:8787"
      - "8686:8686"
  #Below configurations were modified from: https://github.com/confluentinc/cp-docker-images/blob/5.2.2-post/examples/kafka-single-node/docker-compose.yml
  #Zookeeper will be available at `zookeeper:22181`
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000

  #Kafka will be available at `kafka:29092`
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
